### ISSUE TITLE
[meta] Implement all styles that are being dropped from JSHint

### ISSUE THREAD

**Issue by mikesherov** [jscs-dev/node-jscs#102]
As of JSHint 3.0, all style conformance rules are being dropped: https://github.com/jshint/jshint/issues/1339 . JSCS is the perfect tool to reimplement these checks. Hopefully, all can be implemented, as this will help a lot with adoption of JSCS as the defacto style checker. 

Here's all the options being dropped:
- [x] gcl: not necessary as it was a relaxing option for "white"
- [x] white: already covered by the various JSCS options
- [x] onevar: already covered by existing JSCS options
- [x] **PR** https://github.com/mdevils/node-jscs/pull/115 sub: http://www.jshint.com/docs/options/#sub
- [x] **PR** https://github.com/mdevils/node-jscs/pull/114 laxbreak: http://www.jshint.com/docs/options/#laxbreak https://github.com/mdevils/node-jscs/issues/104
- [x] **PR** https://github.com/mdevils/node-jscs/pull/113 laxcomma: http://www.jshint.com/docs/options/#laxcomma https://github.com/mdevils/node-jscs/issues/103 && https://github.com/mdevils/node-jscs/issues/66
- [x] **PR**  https://github.com/mdevils/node-jscs/pull/110 trailing: http://www.jshint.com/docs/options/#trailing https://github.com/mdevils/node-jscs/issues/105 
- [x] **PR** https://github.com/mdevils/node-jscs/pull/118 quotmark: http://www.jshint.com/docs/options/#quotmark https://github.com/mdevils/node-jscs/issues/106
- [x] **PR** https://github.com/mdevils/node-jscs/pull/119 newcap: http://www.jshint.com/docs/options/#newcap
- [x] **PR** https://github.com/mdevils/node-jscs/pull/120 nomen: http://www.jshint.com/docs/options/#nomen
- [x] **PR** https://github.com/mdevils/node-jscs/pull/121 camelcase: http://www.jshint.com/docs/options/#camelcase
- [x] **PR** https://github.com/mdevils/node-jscs/pull/122 noempty: http://www.jshint.com/docs/options/#noempty
- [x] **PR** https://github.com/mdevils/node-jscs/pull/123 immed: http://www.jshint.com/docs/options/#immed
- [x] **PR** https://github.com/mdevils/node-jscs/pull/134 smarttabs: https://github.com/mdevils/node-jscs/issues/60 http://www.jshint.com/docs/options/#smarttabs
- [x] **PR** https://github.com/mdevils/node-jscs/pull/135 maxlen: http://www.jshint.com/docs/options/#maxlen
- [x] **PR** https://github.com/mdevils/node-jscs/pull/137 indent: https://github.com/mdevils/node-jscs/issues/60 http://www.jshint.com/docs/options/#indent
- [x] **PR** https://github.com/mdevils/node-jscs/pull/142 multistr: https://github.com/mdevils/node-jscs/issues/141 http://www.jshint.com/docs/options/#multistr

...

**Comment by popomore** [comment]
Great!
