### ISSUE TITLE
Rule name changes rollup

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1834]
#### Rule Renames
- [ ] [`requireSpacesInsideObjectBrackets`](http://jscs.info/rule/requireSpacesInsideObjectBrackets) -> `requireSpacesInsideObjectBraces` #538
- [ ] [`disallowSpacesInsideObjectBrackets`](http://jscs.info/rule/disallowSpacesInsideObjectBrackets) -> `disallowSpacesInsideObjectBraces` #538
- [ ] [`disallowMultipleVarDecl`](http://jscs.info/rule/disallowMultipleVarDecl) -> `disallowMultipleVariableDeclaration` #1549
- [ ] [`requireMultipleVarDecl`](http://jscs.info/rule/requireMultipleVarDecl) -> `requireMultipleVariableDeclaration` #1549
- [ ] [`requireVarDeclFirst`](http://jscs.info/rule/requireVarDeclFirst) -> `requireVariableDeclarationFirst` #1549
- [ ] [`requireSpacesInGenerator`](http://jscs.info/rule/requireSpacesInGenerator) -> `requireSpacesAroundGeneratorStar` #1963

---
#### Remove deprecated values
- [ ] [`disallowMultipleVarDecl`](http://jscs.info/rule/disallowMultipleVarDecl) - remove legacy option values: `strict` and `exceptUndefined` #1349
- [ ] [`requireSpaceAfterLineComment `](http://jscs.info/rule/requireSpaceAfterLineComment) - remove legacy option value `allowSlash` #697 

---
#### Rework options to use allExcept
- [ ] [`requireCamelCaseOrUpperCaseIdentifiers `](http://jscs.info/rule/requireCamelCaseOrUpperCaseIdentifiers) - change `ignoreProperties` options to use `allExcept` #1303 
- [ ] [`requireDollarBeforejQueryAssignment `](http://jscs.info/rule/requireDollarBeforejQueryAssignment) - change `ignoreProperties` options to use `allExcept` #1303

---
#### Newline name consistency #853
- [ ] `newline` or `newLine` or `NewLine`, `lineBreak`, `lineFeed`, etc

disallowKeywordsOnNewLine
disallowNewlineBeforeBlockStatements
disallowObjectKeysOnNewLine
disallowPaddingNewLinesAfterBlocks
disallowPaddingNewLinesAfterUseStrict
disallowPaddingNewLinesBeforeExport
disallowPaddingNewlinesBeforeKeywords
disallowPaddingNewLinesBeforeLineComments
disallowPaddingNewlinesInBlocks
disallowPaddingNewLinesInObjects
requireBlocksOnNewline
requireKeywordsOnNewLine
requireNewlineBeforeBlockStatements
requireObjectKeysOnNewLine
requirePaddingNewLineAfterVariableDeclaration
requirePaddingNewLinesAfterBlocks
requirePaddingNewLinesAfterUseStrict
requirePaddingNewLinesBeforeExport
requirePaddingNewlinesBeforeKeywords
requirePaddingNewLinesBeforeLineComments
requirePaddingNewlinesInBlocks
requirePaddingNewLinesInObjects
validateNewlineAfterArrayElements

disallowCommaBeforeLineBreak
disallowMultipleLineBreaks
disallowOperatorBeforeLineBreak
requireCommaBeforeLineBreak
requireLineBreakAfterVariableAssignment
requireOperatorBeforeLineBreak
validateLineBreaks

requireLineFeedAtFileEnd

#### Singular vs. Plural
- [ ] ?

#### Function Spacing rules
- [ ] ?
We should combine/deprecated old ones (require/disallow)
- requireSpacesinFunction
- requireSpacesinFunctionExpression
- requireSpacesinFunctionDeclaration
- requireSpacesinNamedFunctionExpression
- requireSpacesinAnonymousFunctionExpression

#### spaces around instead of before/after
- [ ] requireSpaceAroundBinaryOperators - #1476 

If not move all the last 4 rules into requiresSpacesInFunction with options, at least remove named/anon and move into functionexpression. Otherwise for any function spacing rule change we need to change 20 files (example is with supporting `async`)

**Comment by jacksonrayhamilton** [comment]
This doesn't have to be breaking; you could define aliases.

**Comment by hzoo** [comment]
We can do the aliases and then remove in next version yeah.
