### ISSUE TITLE
Version 3.0

### ISSUE THREAD

**Issue by mdevils** [jscs-dev/node-jscs#1854]
This is a roadmap ticket for version `3.0` which we are starting to work on intensively today.

The `master` branch is now for the new `3.0` version. For `2.x`-hotfixes we now have `2.x` branch.

### CST (WIP PR: #1977) (Merged #2101)
The `3.0` version consists of:
 * [x] Using `CST` for checking.
 * [ ] Using `CST` for fixing.
 * [ ] *Deprecating* most of `JsFile` functions (they are duplicative to `CST`).
 * [ ] Operating using `elements` instead of `line, column` in error reporting.
 * [ ] Document what is considered a public API (#1084, #1821)
 - [ ] Fixup skipped tests/all tests pass
 - [ ] Fix TODO comments

### CLI
* [ ] --verbose = true by default (so easier to debug issue by rule name) - https://github.com/jscs-dev/node-jscs/issues/1522
- [ ] Update the internal error message to supply version number, debug info, sample code, etc
- [x] Remove esnext, es6, esprima, esprimaOptions values (on by default / use cst) #2102 #2103 #2104

### Deprecations
* [x] remove deprecated (JSX) [XJS visitors](https://github.com/jscs-dev/node-jscs/blob/9fd87060c16e596c4f9be75e3224d2e569436891/lib/tree-iterator.js#L6-L17)
* [ ] remove all `*deprecated*` options #2110
- [ ] remove all options that aren't `allExcept: {}` and replace them with `allExcept`

### Wishlist
- ~~[ ] Rewrite in ES6 (#1469)~~
- ~~[ ] Perf metrics on rules, parsing, file handling, etc #1043~~
- [ ] A way to create an issue from the cli (with issue template or automated)

### Config Wishlist
- ~~[ ] New structure - https://github.com/jscs-dev/node-jscs/issues/698~~
- ~~[ ] Provide option for config rewrite (basically a command to upgrade a users config from 2.x to 3 automatically so there's a simple upgrade path, same with deprecated)~~
* [ ] Rules rename - https://github.com/jscs-dev/node-jscs/issues/1834  
* [ ] Use json schema for rule input validation - https://github.com/jscs-dev/node-jscs/issues/480 

/cc @markelog @hzoo @zxqfox @mrjoelkemp @mikesherov

**Comment by markelog** [comment]
What is the progress on those points?

> Using CST for fixing.

Can we leave some parts on token manipulating? I think no, right?

Would you mind providing examples for #3 and #4 points? How it was and how it should be? So others could duplicate that

**Comment by hzoo** [comment]
Can check the 3.0 milestone for anything else we want to do or postpone.

**Comment by hzoo** [comment]
Even if we don't get to the new format structure soon - we can try to combine rules that are similar - like maybe the function spacing rules?

**Comment by hzoo** [comment]
Added deprecations, and documenting what is a public API
