### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1866]
- [ ] New Rule for ValidateArrayIndentation #806, #1781
```js
[
  123,
  234
]
```
- [ ] New Rule for ValidateObjectIndentation #806 
```js
{
  "a": 1,
  "b": 2
}
```
- [ ] New Rule for ValidateFunctionCallIndentation #789, #1780

```js
myFoo(
  2,
  4
)
```
- [ ] New Rule for ValidateModuleIndentation (ES6)

```js
import {
  methodA,
  methodB
} from './module'
```

**Comment by bjdixon** [comment]
These would accept the same values as ``` validateIndentation ``` except the deprecated value ``` validateIndentation: { includeEmptyLines }```, right?

 * Integer: A positive number of spaces
 * String: "\t" for tab indentation
 * Object:
   * "value": (required) the same effect as the non-object values
   * "allExcept":
     * "comments"
     * "emptyLines"

**Comment by hzoo** [comment]
Yeah I would think so

**Comment by hzoo** [comment]
We released [3.0](https://github.com/jscs-dev/node-jscs/releases/tag/v3.0.0)! We also wrote a [post](https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2#.oot3wvgpu) about how 3.0 will be our last major release and that we are [merging with ESLint](http://eslint.org/blog/2016/04/welcoming-jscs-to-eslint).

So we won't be working on any new features moving forward including new rules/options. We will continue to fix bugs and work on CST and better autofixing for current rules in the upcoming months.

I'm putting an `orphaned` label to note this isn't being worked on unless someone wants to do a PR.
